global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-temash7904.2sem.students-projects.ru # Корректный домен будет указан в задании
    tlsSecret: 2sem-students-projects-wildcard-secret
    path: /
    pathType: Prefix
  containerPort: 80
  image: docker7904/sausage-store-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
  ### Опишите стратегию RollingUpdate для бэкенда
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  image: docker7904/sausage-store-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
  ### Опишите LivenessProbe для бэкенда
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
  vpa:
  ### Опишите VPA для бэкенда
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          controlledResources: [cpu, memory]

backend-report:
### Опишите значения для backend-report
### Приложение должно использовать стратегию Recreate
### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb. 
### DB положите в Secret, PORT в ConfigMap
### Опишите HPA для backend-report
  image: docker7904/sausage-store-backend-report:latest
  replicas: 1
  strategy:
    type: Recreate
  env:
    port: 8080
    db: mongodb://reports:reportspassword@mongodb:27017/sausage-store
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    averageUtilization: 70
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

infra:
  postgresql:
  ### Опишите необходимые переменные для развертывания PostgresQL в кластере Kubernetes
    image: postgres:14-alpine
    database: sausage-store
    username: store
    password: storepassword
    storage: 1Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
